### ISSUE TITLE
The Repository version doesn't match the one on crates.io

### ISSUE THREAD

**Issue by evaporei** [AlexPikalov/spy#6]
The last crates.io version of `spy` was published in June of 2018, however that version is broken. Now that we've made the fixes on the repository, we should publish so that people can download the corrected version via `cargo`. 🙂

**Comment by evaporei** [comment]
Now that we have a Pull Request, after the merge, a `cargo publish` should be executed with the new code.

**Comment by AlexPikalov** [comment]
@otaviopace 
Thanks for the fix. I'll publish it asap

**Comment by AlexPikalov** [comment]
@otaviopace `0.1.1` was published to crates.io

**Comment by evaporei** [comment]
Yesssssssssssssss :tada: :confetti_ball: 
Thank you sooo much for the help :heart:

**Comment by AlexPikalov** [comment]
Thank you too
